services:
  web:
    build: ./web
    volumes:
      - ./web/html:/usr/local/apache2/htdocs
      - ./web/cgi-bin:/usr/local/apache2/cgi-bin
    ports:
      - 80:80
    depends_on:
      - backend
  backend:
    image: mysql:8.0
    volumes:
      - ./container_db_volume:/var/lib/mysql
      - ./mysql_db_files/insert_data.sql:/docker-entrypoint-initdb.d/insert_data.sql
    ports:
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
volumes:
  container_db_volume: